docs/quickstart/build_setup.md
docs/quickstart/config.md
docs/quickstart/init.md

Let's use your repository as the temporary official one and start updating the docs there. This way we don't forget to update the docs at release time and we don't interfere with the wiki that others may be looking at during the month.

docker: document single dockerfile

---

docs/install/index.md

Installing with `pipenv install --pre`, install 1.0.0a9 which is **not** what we want.

cli: install via pipenv w/o --pre

---

docs/index.md

Link to develop used to link to preview.

home: fix link to develop section

---

docs/develop/cleanup.md
docs/develop/config.md
docs/develop/customize.md
docs/develop/index.md
docs/develop/install_locally.md
docs/develop/run.md
docs/develop/troubleshoot.md
docs/extensions/custom.md
docs/extensions/s3.md
docs/install/index.md
docs/preview/index.md

- Separate commands to be entered (`bash` syntax to pop) and
returned output (`console` syntax to be muted), so that commands can be
copied via the clipboard icon directly. Closes #6
- Removed permission configuration advanced example temporarily given it wasn't
working.
- Documented more details of the workflow:
* how checking for running containers incurs a 30s delay
* how server must be stopped and started whenever invenio.cfg is changed
- Moved some small sections around for clarity and focus.
- Did a pass at all syntax highlighting to make everything pop
as much as possible (jsx doesn't work so broken js was used for jsx :shrug:)
Easiest way to assess is by running it locally.

global: separate commands and output and [more]

---

docs/develop/config.md

Reintroduce the removed "advanced example", but just make it part of the normal flow (not advanced) and add missing step.
closes https://github.com/inveniosoftware/invenio-records-permissions/issues/43

config: add steps to permission configuration

---

docs/install/index.md

In the docs it is stated:
```
Python (3.6.2 <= supported version < 3.7.0 only)
nodejs (8.0.0+) (not needed to preview, only needed to develop)
Docker (1.13.0+)
Docker-Compose (1.17.0+)
```
As discussed IRL, Python 3.7 support cannot still be said since there is no docker image for it.
nodejs 8 is out of support https://nodejs.org/es/about/releases/. Between us and the Zenodo team we have run RDM in node versions 7, 8, 11, 12 and 13. Any of you @fenekku @zzacharo with node 10?
Docker support seems fine. It is running fine also with but I see no need to bump those since my old laptop IIRC was the lowest (the current ones on the website) and it was running fine:
```
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.4, build 8d51620a
```
Closes …

pre-requirements: bump deprecated versions

---

docs/deployment/benchmark.md
docs/deployment/openshift.md
mkdocs.yml

Adds:
* Populating the instance with rpm-records demo. Points to the bulk indexing used in helm-invenio, which is much more performant (3M records in a few hours). I think `rdm-records` should stay as is, 10 records is more than enough and is better not to add complexity. WDYT?
* How to use locust and points to the locust.py file.
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/34

benchmark: populating your instance and stress test with locust

---

docs/deployment/image.md
docs/deployment/openshift.md
docs/deployment/registries.md
mkdocs.yml

This PR adds documentation on how to build the docker image for InvenioRDM and how to push it to several registries (GitHub, OpenShift and DockerHub).
Requires: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/56
**Question**:
Since GitHub requires a password/token stored in OpenShift. Options are:
a. We can leave it as is, and make the user build the image (2-3 mins) and push it to a registry.
b. Build the default image (that we have to do anyway) and push it to DockerHub so everybody has access to pull it.
Note: if we opt for a we can just push our image to CERN OpenShift or CERN GitLab registry.
WDYT? @lnielsen @zzacharo @fenekku 
Decision will close https://github.com/inveniosoftware/demo-inveniordm/issues/7

deployment: building images and pushing to a registry

---

docs/develop/make_it_your_own.md

Adds missing "creators" to record creation example of extensions section.
See https://github.com/inveniosoftware/invenio-rdm-records/issues/86 for next steps to do next month.

extensions: add required 'creators'

---

docs/develop/make_it_your_own.md

- Add token creation through CLI
- Add description to POST operations to avoid breaking search UI. It is used [here](https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/assets/templates/search/ResultsItemTemplate.jsx). Two options, make it not mandatory, somehow people should reimplement their UI templates if they don't want it?
- Add identifiers and community fields. Records landing page template is not yet ready to be rendered without this fields. https://github.com/inveniosoftware/invenio-rdm-records/issues/70

global: fix outputs and commands to align with v0.7.0

---

docs/develop/index.md
docs/develop/make_it_your_own.md
docs/develop/run.md
docs/install/index.md
docs/preview/index.md

**NOTE**: We have configured `/rdm-records` without end slash and there is no redirect. We should fix that for next release.

global: several updates on endpoints and python versions

---

docs/develop/make_it_your_own.md
docs/develop/run.md
docs/install/index.md
docs/preview/index.md

- added python development headers as a pre-requisite based on other developers' experience 
- removed "aggregations" from result examples since disabled for this release
- switched examples from localhost to 127.0.0.1 since that is use in links generation
- added `publication_date` and other tweaks to requests and responses
- highlighted some of the changes for the August release

global: update docs for august release

---

docs/develop/make_it_your_own.md
docs/develop/run.md

Changing permissions is still possible. How to do so had slightly changed, so I updated the docs to reflect that.
This approach is actually the same to customize facet or sorting (i.e. already implemented and tested: https://github.com/inveniosoftware/invenio-records-resources/blob/master/tests/services/test_configuration.py, https://github.com/inveniosoftware/invenio-records-resources/blob/master/tests/services/test_service_facets.py, and so on... ).
closes https://github.com/inveniosoftware/invenio-records-resources/issues/127
closes https://github.com/inveniosoftware/invenio-records-resources/issues/92

global: document permission change

---

docs/develop/cleanup.md
docs/develop/edit_a_module.md
docs/develop/index.md
docs/develop/install_locally.md
docs/develop/make_it_your_own.md
docs/develop/run.md
docs/develop/troubleshoot.md
docs/install/index.md
docs/preview/index.md
mkdocs.yml

Closes #76 
Changes:
- Move all docker hardware allocation notes to pre-requisites
- Migrate `SERVER_HOSTNAME` to `SITE_HOSTNAME`. Instruct the use of `--host` and `--port` for `invenio-cli run`.
- Remove the need to export `FLASK_ENV`, use `--development/-d` flag
- Change `Notes and Known Issues` sections from bold to h4 (still displays equally), but allows sending it as link (which is helpful when sending info to partners when troubleshooting/testing).
- Reference `stop` command, remove `--local/--containers` flags from `destroy` command.
- Migrates any reference to the old `invenio-cli update [--no-install-js]` command to the new `invenio-cli assets update [--force]`.
**Adds**:
- A new section `develop/edit_module.md` to explain how to setup and develop CSS and React.

November release review

---

docs/develop/run.md

1.  field ```files``` set to ```true```
```diff
- "files": false,
+ "files": true,
```
since we are using the same record below to add files to it it is required to set the value ```true```.
also changed the outcome for searching the record value to ```true```.
2. (bug) removed the extra comma
removed unnecessary extra comma, and formated the 'closing single quotation mark` so that the user is able to see it.
```diff
-   {"key": "leaf_doge.jpg"},
- ]
-  '
+  {"key": "leaf_doge.jpg"}
+ ]'
```

docs: fixing typos

---

docs/preview/index.md

In the current release, the host variable in invenio.cfg is already set to 127.0.0.1, so these instructions are no longer needed.

Remove host details

---

docs/extensions/custom.md

The `invenio-cli packages install` command now uses pip under the hood. Therefore this check is not needed anymore.

extensions: remove pipfile check

---

docs/develop/make_it_your_own.md

Within the last releases `BibliographicRecordServiceConfig` was renamed
to `RDMRecordServiceConfig` (and moved?). Adjusting the import and name
makes it work again.
Refs https://github.com/inveniosoftware/docs-invenio-rdm/issues/116

Fixes permission code-example.

---

docs/develop/make_it_your_own.md

Refs https://github.com/inveniosoftware/docs-invenio-rdm/issues/118
As mentioned in
https://github.com/inveniosoftware/docs-invenio-rdm/issues/116 the
`BibliographicRecordServiceConfig` was renamed to
`RDMRecordServiceConfig`. The code example was fixed in
https://github.com/inveniosoftware/docs-invenio-rdm/issues/116 but the
text wasn't. This is done here.

Renames BibliographicRecordServiceConfig to RDMRecordServiceConfig.

---

docs/develop/index.md

In the suggested workflow, there's no need to activate a virtual environment when developing on the CSS/templates (e.g. `invenio-app-drm`) or on the react modules. It can create confusion to tell people to activate a virtualenv when it was never mentioned to create one in the first place (as opposed to the workflow for separate modules, e.g. invenio-cli itself).
The tested flow:
```
pip install invenio-cli
invenio-cli check-requirements --development
invenio-cli init rdm
cd my-site/
invenio-cli install
invenio-cli services setup
invenio-cli run
invenio-cli packages install invenio-app-rdm
invenio-cli assets watch
```

Remove mentions of virtual environments

---

docs/reference/cli.md

Add warning in documentation for installing services: make sure Postgres is not installed locally (and using port 5432) when installing the database service and using Postgres. Closes inveniosoftware/invenio-cli#266.

Add warning in documentation for installing services

---

docs/customize/vocabularies/users.md

- Makes reference 'this file' which wasn't named before explicit.
- Switches two sentences to improve reading flow.
- Removes sentence that seems out of place (at the bottom of the file) and seems to be doubled with a sentence before.

Adjusts documentation

---

docs/customize/styling-theme.md

Fix in cookiecutter: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/201
Note: You can do all these variable-overwrites also in the overrides files, but I think it is conceptually wrong: https://semantic-ui.com/usage/theming.html#theme-files see "Composing a Component" difference 'variables' and 'overrides'
In 'variables' you could also change
```
@blue: @brandColor;
```
Which is not working if you put it in overrides.
If this patch is not accepted and the variable-overwrites should go in overrides then the documentation would need the following alternative adjustment:
``` less
@import "@less/invenio_app_rdm/variables";
@import "site.variables";
@brandColor: /* your brand color here */ ;
@navbar_background_image: unset;
@navbar_background_color: @brandColor; …
```

Updates documentation wrt. fix in cookiecutter

---

docs/customize/vocabularies/users.md

The format of the users.yaml file seems to be different from what is expected in the code, correct me if i am wrong. It is also not clear, from first sight, that the example is a singular item that has to be inside a *list*

Customize: updated users.yaml format

---

docs/reference/metadata.md

Fix typo in the description of the award identifier

metadata: fix description of award identifier

---

docs/reference/metadata.md
docs/stylesheets/extra.css

- doc issues brought to attention by @marijane
- Also finally fixed word-break for code fields in tables!
e.g., before:
after:
(but now for all)

metadata: correct doc for locations + references [+]

---

docs/reference/index.md

Contains some fixes in the [overview](https://github.com/inveniosoftware/docs-invenio-rdm/blob/c7929894a2fa77a0672a0fff9e0288a7b92b10af/docs/reference/index.md) of the reference documentation:
- Fixed the description of the CLI section, which incorrectly referred to the REST API reference guide. The new description was copied from the [CLI reference guide](https://github.com/inveniosoftware/docs-invenio-rdm/blob/c7929894a2fa77a0672a0fff9e0288a7b92b10af/docs/reference/cli.md?plain=1#L5).
- Fixed some minor punctuation inconsistencies.

reference: fix description and punctuation in overview

---

docs/customize/vocabularies/users.md

- Updated the user object in the documentation to show the profile information which can be included.
- Added an example of how you can confirm the user using the invenio shell
needs https://github.com/inveniosoftware/invenio-rdm-records/pull/970

users: update docs

---

docs/install/requirements.md

Git is not mentioned as a requirement, but `invenio-cli init rdm -c <version>`, the suggested scaffolding option, will fail if the git executable is not found, even if `invenio-cli check-requirements` succeds.
I will follow up with a later PR to make `invenio-cli check-requirements` look for git, too.

Mention git as system requirement

---

docs/features/powerful.md
docs/reference/metadata.md

- features: fix search-as-you-type typo closes #391 
- metadata: align funding docs with current functionality in invenio-rdm-records/invenio-vocabularies

update funder references metadata docs

---

docs/customize/vocabularies/funding.md
docs/customize/vocabularies/names.md

- requires https://github.com/inveniosoftware/invenio-vocabularies/pull/203
- partly closes #384 
by not setting the service name, it had to be stated twice in the yaml file.
Before:
```yaml
writers:
- type: funders-service
args:
service_or_name: funders
identity: system_identity
```
Now
```yaml
writers:
- type: funders-service
args:
identity: system_identity
```

vocabularies: contrib should not need to specify service twice

---

docs/install/index.md

This PR aims to provide a basic reference point for creating an account and giving it administrator privileges.
Some points I think they should be discussed (optionally outside of the scope of this):
- It's very confusing to have "invenio" and "inveino-cli" commands in the quickstart guide for trying-out InvenioRDM locally. I think the two need to be introduced (or at least disambiguated)
- It still feels a bit out of context to talk about this in the QuickStart deploy locally instructions, I think this may be better fitted in Use of Configure, if a new section can be created there for this
- Make the usage of "User" and "Account" terms more consistent, as it can lead to confusion
- Add a new section for the User Management (why is it in Vocabularies? it feels like very specific to the …

Mention how to create an (administrator) account

---

docs/releases/versions/version-v11.0.0.md

Fix typo in funders description

---

docs/reference/metadata.md

The metadata document indicates that the `access` field is required, but that's not accurate. The REST API is perfectly happy to create a record with public access if `access` is not provided.
**Reminder**

Fix access requirements

---

docs/develop/architecture/records.md

"only published changes which a tracked" should be "which are tracked".
I think the word "happens" in the sentence before this could also be removed but maybe I just don't understand it.

Fix typo in develop/architecture/records.md

---

docs/develop/architecture/infrastructure.md

Updating the infrastructure part of the documentation, putting OpenSearch instead of OpenSearch
**Reminder**
1. You license your contribution under the same terms as the current repository’s …

opensearch: Replace Elasticsearch by OpenSearch

---

docs/develop/howtos/i18n.md

This PR adds a note to the documentation to clarify the role of absolute paths in .po and .pot localization files.
Users may be confused about the presence of absolute paths in these files. The note explains that these paths serve as comments for human context and do not impact the compiled .mo file or the application's behavior.
**Reminder**
By using GitHub, you have already agreed …

i18n: Clarify absolute paths in .po and .pot files

---

docs/develop/topics/rest.md

minor fix, when searching the documentation page for "rest api" the result is the develop rest api page which is empty whereas most will be looking for the reference page
also, and more alarming, when searching for "rest api" the reference for rest api is NOT among results

clarify empty rest api page

---

docs/customize/static_pages.md

Place the admin panel under v12, as its current positioning misleadingly suggests that v11 includes this feature.
**Reminder**
1. You license your contribution under the same terms as the current …

Customize: Nest static page admin panel under v12

---

docs/customize/authentication.md

- Add GitHub authentication integration.
- Update ORCID import to match.

Customize: Add GitHub authentication integration

---

docs/reference/rest_api_drafts_records.md

Custom fields isn't called out like the other top-level options in the REST API
**Reminder**
2. You …

rest: add custom_fields as parameter

---

docs/contribute/index.md
docs/deploy/index.md
docs/develop/howtos/custom_fields.md
docs/install/cli.md
docs/reference/index.md
docs/releases/upgrading/upgrade-v3.0.md
docs/releases/upgrading/upgrade-v6.0.md
docs/releases/versions/version-v3.0.0.md
docs/releases/versions/version-v4.0.0.md
docs/stylesheets/extra.css
mkdocs.yml
requirements.txt
theme/frontpage_base.html

- links: remove warnings by using .md reference
- mkdocs-material: upgrade to 9.x
- closes #591 
Look-n-feel kept the same as much as possible. Main difference:
**before**
**after**

Pass CI / Upgrade mkdocs-material

---

docs/customize/look-and-feel/font.md
mkdocs.yml

Add instructions for changing fonts locally
**Reminder** …

Customize: Add instructions for changing fonts

---

docs/customize/look-and-feel/theme.md

Customization: Add instructions for changing search button color

---

docs/customize/Logging.md
mkdocs.yml

- added logging documentation.
This submission initiates the documentation for the logging feature. There may be some aspects I've overlooked; kindly review and supplement any omitted details, such as `InvenioLoggingConsole`, `InvenioLoggingFS`.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-serv …

Customization: Add Logging

---

docs/reference/cli.md

Resolves confusion documented at https://github.com/inveniosoftware/invenio-app-rdm/issues/2608 by adding more details about how reindexing works.
**Reminder**
1. You license your contribution …

cli: Add warnings to reindex command

---

docs/reference/rest_api_drafts_records.md

Add two sentences below the **Files Options** section noting that `files.default_preview` won't work for files that aren't added to the draft yet. I think that the ordering of this document, which first discusses creating a draft with files options included and then later adds the files themselves, makes it unclear the file must be added first. As I started working with the REST API, this would have been useful to know.
`files.order` does not work but I didn't mention that, I couldn't find a precedent for writing Invenio bugs into the documentation, but I could add a note about that too, if desirable.
* If you have added [third-party code (copy/pasted or new …

reference: add file before setting default_preview

---

docs/customize/vocabularies/names.md

Also fix the case from "ORCiD" to "ORCID".
The current link points to the ORCID dataset from 2021. The proposal is to change the link to some ORCID documentation which contains the list of the datasets of all years.
I also changed the case from "ORCiD" to "ORCID" since I did not find any official places using this mixed casing.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the …

vocabularies: names: link to datasets for all years

---

docs/customize/index.md
docs/customize/notifications.md
docs/develop/architecture/notifications.md
docs/develop/howtos/notifications.md
docs/develop/index.md
docs/reference/index.md
docs/reference/notifications.md
mkdocs.yml

closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2204
Adds notification documentation to the reference and customization sections.
**Reminder**
1. You license your contribution …

docs: add notification section to customize and reference

---

docs/develop/getting-started/instance-development.md

This adds an option to install a fork in a Pipfile, with a warning that this is only recommended in limited cases. Setup mostly from @Samk13 
**Frontend**
**Reminder**
1. You license your contribution under the …

Add fork install option

---

docs/reference/metadata.md
docs/reference/rest_api_drafts_records.md
docs/releases/versions/version-v12.0.0.md

Seemingly `parent.access.owned_by` underwent a breaking change in the REST API. This PR documents it. (Unless this is a bug)
What was the reasoning for not keeping it as an array (of length 1)? 
**[EDIT from discord discussion]**
This is actually in keeping with Zenodo's API (see https://github.com/zenodo/zenodo-rdm/blob/master/invenio.cfg#L339).

metadata: document parent.access.owned_by breaking change

---

docs/develop/howtos/backup_search_indices.md

This PR adds small `bash` scripts to back up/restore all `stats` indices in one go to the corresponding how-to section.
It's based on shell scripts that I'm currently writing for our own instances.

how-to: add example bash scripts for backing up stats indices

---

docs/releases/upgrading/upgrade-v12.0.md
docs/releases/versions/version-v12.0.0.md

As I am actually going through the upgrade, I am adjusting v12 notes with important bits.
I may make other PRs like this in the future, but making those fixes public is more important than waiting for hypothetical future ones.

release-notes v12: fix typos

---

docs/reference/search.md
mkdocs.yml

closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/2778

Reference: Add suggest API guide and custom index settings docs

---

docs/customize/vocabularies/names.md

* closes https://github.com/inveniosoftware/invenio-vocabularies/issues/353

names: add ORCiD public data sync

---

docs/customize/vocabularies/names.md
docs/reference/search.md
docs/releases/upgrading/upgrade-v13.0.md
docs/releases/version-v13.0.0.md
docs/releases/versions/version-v10.0.0.md
docs/releases/versions/version-v13.0.0.md
mkdocs.yml

This is just taking the appropriate commits on `dev` not found on master and bringing them to `master` now that master is the "new dev". Those are v13 documentation commits. Will merge this as soon as tests pass.
- **v13: add draft release notes**
- **add missing files**
- **Reference: Add suggest API guide and custom index settings docs**
- **Reference: Update suggest API guide to reference edge_ngrams**
- **Reference: Add InvenioRDM version 13 in docs**
- **Reference: small fixes to wording**
- **names: add ORCiD public data sync**
- **fix v10 links and add v13 links**
- **v13: add show packages version in admin panel**
- **WIP: v12 to v13 upgrade**

dev to master

---

docs/reference/metadata.md

That was reported by a user, so updated `References` section and made a referenceable (ha!) section for scheme identifiers.

references: remove deposit page warning + update list

---

docs/releases/v13/version-v13.0.0.md

collections: added feature overview

---

docs/releases/v13/upgrade-v13.0.md

This PR documents the change in the `nginx.conf` that's necessary for the new `pdfjs-dist` v4-based PDF previewer (from `Invenio-Previewer` v3.x) to work.

v13: document necessary nginx config change for pdfjs-dist v4

---

docs/develop/getting-started/debugging.md

Add VS Code debugging configuration
**Reminder**

docs: add VS Code debugging config

---

docs/reference/rest_api_communities.md

owned_by was removed in 2022 in https://github.com/inveniosoftware/invenio-communities/commit/14c4768e1c8d2ab2ed2cb254fc82ffd5a5d3b779#diff-fdb214e572f1f6740d9290cb190a449bf6abd4da7073797e349df6836a31052e.
This will need to be backported to `production`.
**Reminder**

communities api: remove owned_by

---

docs/reference/rest_api_communities.md

Removes lingering references to the field "owned_by" that itself was under "access".
**Reminder**

communities api: remove lingering refs to owned_by

---

docs/develop/howtos/i18n.md

Read the comment on Discord: https://discord.com/channels/692989811736182844/852219787005919242/1336648054488567868
**Reminder**

docs: update i18n guidelines for string interpolation in Python

---

docs/customize/emails.md
docs/develop/howtos/dev_email.md

Update dead links to the documentation for "flask-mail," which has moved to [readthedocs](https://flask-mail.readthedocs.io/en/latest/)
**Reminder**

docs: update broken links for flask-mail config

---

docs/customize/Logging.md
docs/releases/v13/upgrade-v13.0.md

I think this change will be needed for v13 once invenio-logging is updated.
**Reminder**

Add updated sentry instructions

---

docs/index.md
docs/releases/index.md
docs/releases/maintenance-policy.md
theme/frontpage.html

- From 2025-03-10 DWG action item.
- Includes a fix for frontpage "Legacy Versions" link wrongly linking to frontpage.

releases: clarify language around how long releases are supported

---

docs/customize/emails.md

Copies the notification email config from https://inveniordm.docs.cern.ch/releases/v11/version-v11.0.0/#reports to the email section.
**Reminder**

emails: add notification email details

---

docs/releases/v12/version-v12.0.0.md

This documents the fact that https://github.com/inveniosoftware/invenio-rdm-records/pull/2037 won't be backported to v12.

v12: add known issue about `RDMRecordQuota.user_id` uniqueness

---

docs/reference/cli.md
docs/reference/cli_invenio.md
docs/use/administration.md
mkdocs.yml

Closes: https://github.com/inveniosoftware/docs-invenio-rdm/issues/719
**Reminder**

Docs: Split CLI section into invenio and invenio-cli with detailed command descriptions

---

docs/maintenance/architecture/curation.md
docs/operate/customize/curation-checks.md
docs/reference/checks_config.md
docs/releases/v13/version-v13.0.0.md
mkdocs.yml

v13: add curation checks documentation

---

docs/operate/customize/notifications.md

* The current notifications builder example removes all the builders
Invenio-App-RDM configures resulting in several exceptions raised when
running it due to missing builders.
**Reminder**

docs: fix notifications customize example

---

docs/reference/cli.md

Quick fix for typos in services and containers setup command option.

docs: fix typo in setup cmd options

---

docs/operate/customize/metadata/custom_fields/widgets.md

Closes https://github.com/inveniosoftware/react-invenio-forms/issues/297
* As part of https://github.com/inveniosoftware/react-invenio-forms/pull/298, UI widgets are being given a standardised common set of props (on top of which each widget can have additional, more specific props)
* This PR changes the reference docs for custom field widgets by splitting into the two distinct sections of "common props" and "widget-specific props"
* Some of the prop names have been updated to stay consistent with the names we use for the built-in deposit form fields (e.g. `description` -> `helpText`) so this has been reflected in the docs.

docs: operate: common props for UI widgets

---

.github/pull_request_template.md

This PR aims at fixing broken links in the Github PR template.
**Reminder**

minor: fix broken links in PR template

---

docs/reference/rest_api_communities.md

The REST API lets you specify the members visibility and review policy of communities but this isn't in [the documentation](https://inveniordm.docs.cern.ch/reference/rest_api_communities/#community-access).
Someone should check my work here but in my testing these are the correct options and defaults. The fields definitely are optional because community creation requests without them work fine.
**Reminder**
1. You license your …

Add 2 fields to Community Access REST API
