inveniosoftware/docs-invenio-rdm

- README.md
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/8
> readme: fix URL and remove travis badge

- docs/develop/customize.md
- docs/develop/index.md
- docs/develop/run.md
- docs/extensions/custom.md
- docs/extensions/index.md
- docs/extensions/s3.md
- docs/index.md
- docs/install/index.md
- docs/preview/index.md
- mkdocs.yml
Changes:
- Adds some more pre-reqs
- Beautify notes and warning with ademonition
- Adds how to integrate custom extensions in RDM
- Adds how to set up S3
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/3
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/4
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/11
> more pre-reqs, how-to-add extensions and S3

- mkdocs.yml
> nav: Fix menus

- docs/develop/customize.md
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/9
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/10
> customize: how to change colors

- docs/develop/config.md
- docs/develop/install_locally.md
- docs/develop/run.md
- docs/install/index.md
- docs/preview/index.md
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/16
> run/config: update outpus with new data model

- docs/install/index.md
> install: state python >=3.6.2,<3.7.0

- docs/deployment/configuration.md
- docs/deployment/index.md
- docs/deployment/openshift.md
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/33
> deployment: improve explanations on helm usage

- docs/develop/cleanup.md
- docs/develop/index.md
- docs/develop/make_it_your_own.md
- docs/install/index.md
- docs/preview/index.md
- requirements.txt
Changes:
- Update pre-requisites version
- Add warnings about python versions and others.
- Add warnings of out-of-date documentation (e.g. customization)
> global: update content to May release

- docs/develop/make_it_your_own.md
- docs/develop/run.md
- docs/preview/index.md
- Jamming all docs update on this branch
> Docs may update

- docs/develop/run.md
Document changes to the affiliations field.
See https://github.com/inveniosoftware/invenio-rdm-records/issues/128
> run: sync with affiliations changes

- docs/develop/make_it_your_own.md
> removed extra comma

- docs/develop/index.md
- docs/develop/make_it_your_own.md
- docs/develop/run.md
- docs/preview/index.md
I approve of these changes so will merge :)
> Docs update for 0.15.0

- docs/install/index.md
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/71
> install: add docker requirements

- docs/develop/make_it_your_own.md
keeping up with recent folder structure change in invenio-rdm-records. Perhaps there are more elsewhere.
> global: document permission policy import path change

- docs/develop/install_locally.md
- docs/develop/run.md
- docs/install/index.md
- docs/preview/index.md
Docs update
More to follow tomorrow.
> global: update october release docs until develop/run.md (inclusive)

- docs/deployment/openshift.md
- docs/develop/cleanup.md
- docs/develop/edit_a_module.md
- docs/develop/make_it_your_own.md
- docs/develop/run.md
- docs/extensions/custom.md
- mkdocs.yml
> global: more updates for october release

- docs/develop/edit_a_module.md
- docs/develop/make_it_your_own.md
- docs/index.md
- also add metadata reference to main page
- contribute section coming in another pr
> develop: enhance docs with workflow from customization exp.

- docs/index.md
- docs/reference/cli.md
- mkdocs.yml
Reference documentation for https://github.com/inveniosoftware/invenio-cli/pull/182
> reference: add invenio-cli reference documentation

- docs/contribute/index.md
- docs/index.md
- mkdocs.yml
- Also change 'Extensions' to 'Extend' to make all sections action verbs.
- closes #86
> contribute: add contribution + release process docs [+]

- docs/reference/rest_api.md
- mkdocs.yml
> reference: add REST API

- docs/develop/make_it_your_own.md
Document what to edit to get a theme change.
> make_it_own: update theming doc

- docs/install/index.md
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/106
> install: update npm requirements and recommend nvm for node

- docs/develop/install_locally.md
- docs/develop/run.md
* removed warning for using ```--no-demo-data```
* updated response for ```GET``` since the schema was not matching to the new release.
* added a ```info``` on ```Create record``` section.
* updated ```create draft``` json data to match the new schema.
...
> docs: update for feb release

- docs/develop/make_it_your_own.md
- closes #109 
- No need for changes in app-rdm for this one
> make-it-own: document template override

- docs/develop/make_it_your_own.md
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/697
> make-it-your-own: fix docs about less variables

- docs/reference/metadata.md
- docs/reference/rest_api.md
- update all sections except for files + vocabularies
- restructure docs to document Drafts first, then Records, then User records
- update access metadata reference
> api: update + add versions & access links docs

- docs/releases/upgrading/scripts/upgrade-rdm-1.0-to-2.0.sh
- docs/releases/upgrading/upgrade-v2.0.md
add description of required steps (along with a script doing exactly those) for upgrading InvenioRDM v1.0 to v2.0
> upgrade: add description of upgrade procedure from v1.0 to v2.0

- docs/releases/upgrading/upgrade-v2.0.md
mention the local installation of InvenioRDM 1.0 as prerequisite explicitly
> upgrade: update documentation of upgrade from v1 to v2

- docs/install/install.md
Fixes https://github.com/inveniosoftware/docs-invenio-rdm/issues/133
> Mention admin user account creation commands

- docs/reference/rest_api.md
closes inveniosoftware/invenio-app-rdm#738
> restapi: add suggest parameter to vocabularies

- docs/reference/metadata.md
- docs/reference/rest_api.md
- account for files.enabled part of Draft/Record API
- close #123
- close #122
- Still open question about degree of removal of files options from
Files API (+ implementation first).
- close #115
- close #88
> files.enabled adjustments [+]

- docs/reference/rest_api.md
Closes https://github.com/inveniosoftware/invenio-communities/issues/236
> docs: update /api/communities end points

- docs/releases/upgrading/scripts/fix_migrated_records_from_1_0_to_2_0.py
- docs/releases/upgrading/upgrade-v2.0.md
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/744
> upgrade: Add troubleshooting section for upgrade from v1.0 to v2.0

- docs/customize/dois.md
- docs/customize/index.md
- mkdocs.yml
> customize: how to enable doi registration

- docs/customize/disabled.md
- docs/deployment/index.md
- docs/install/build-setup-run.md
- docs/install/configuration.md
- docs/install/index.md
- docs/install/requirements.md
- docs/install/run.md
- docs/install/scaffold.md
- docs/reference/metadata.md
- docs/reference/rest_api.md
- docs/releases/versions/index.md
- mkdocs.yml
This is a series of fixes from a pass over the whole documentation for the April release. 
The `SITE_HOSTNAME` to `SITE_API_URL` / `SITE_UI_URL` transition has been documented so that containerized setup instructions indicate what to change. The https://github.com/inveniosoftware/invenio-app-rdm/issues/782 issue captures what needs to be fixed - any frontend interaction that uses the links from the response are obviously affected if the URLs are not configured properly.
> global: update for april release

- docs/customize/dois.md
- docs/customize/index.md
I think there was a typo in the documentation, but I may be wrong...
> doi: clarify the text [+]

- docs/customize/authentication.md
> auth: add section about integrating Keycloak

- docs/install/requirements.md
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/156
> Add DejaVu Font link

- docs/customize/authentication.md
add some more details about the Keycloak integration
> auth: add some more details for Keycloak

- docs/customize/authentication.md
* add details about local login, oauthclient and their configuration
> auth: add more documentation on authentication

- docs/releases/upgrading/upgrade-v4.0.md
- mkdocs.yml
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/854
> upgrade: document upgrade to v4.0

- docs/releases/upgrading/upgrade-v4.0.md
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/854
> upgrade-v4: updates docs

- docs/reference/rest_api.md
- docs/releases/upgrading/upgrade-v4.0.md
- docs/releases/versions/version-v4.0.0.md
- last documentation updates on my side
- merging this into master and pushing to maint
> global: update may upgrade / release notes

- docs/install/requirements.md
- docs/releases/upgrading/upgrade-v4.0.md
requires https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/162
closes #173
> pre-requisites: add imagemagick to pre-req and v4 upgrade

- docs/maintenance/release-management.md
add dependency from communities to rdm-records
related to https://github.com/inveniosoftware/invenio-rdm-records/issues/636
> release chain modules update

- docs/customize/index.md
- docs/customize/record_landing_page.md
- docs/reference/configuration.md
- mkdocs.yml
* closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/179
> citations: Adds citations docs

- docs/customize/authentication.md
Just groups together all of @chriz-uniba 's PR into one. It was easier that way for added rewording. 
Closes:
https://github.com/inveniosoftware/docs-invenio-rdm/pull/178
https://github.com/inveniosoftware/docs-invenio-rdm/pull/177
https://github.com/inveniosoftware/docs-invenio-rdm/pull/176
https://github.com/inveniosoftware/docs-invenio-rdm/pull/175
> authentication: incorporate chriz-uniba typo fixes

- docs/reference/rest_api.md
- This incorporates @zzacharo's notes and mine.  
- Only the communities REST API has not been tested at this point (communities are in preview / more knowledgeable people would know best)
> rest: update reference for v5.0/fix typos

- docs/deployment/openshift.md
- docs/install/build-setup-run.md
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/782
> global: remove SITE_HOSTNAME

- docs/stylesheets/extra.css
- theme/frontpage.html
> frontpage: add correct gradient and scale hero-bg for large screens

- theme/frontpage.html
* closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/200
> frontpage: remove fixtures display

- docs/customize/application_data.md
- docs/customize/authentication.md
- docs/customize/dois.md
- docs/customize/index.md
- docs/customize/metadata.md
- docs/customize/permissions.md
- docs/customize/s3.md
- docs/customize/styling.md
- docs/stylesheets/extra.css
- mkdocs.yml
* Adds s3 storage to customize
* Css fix on navbar
* needs https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/191
> customize: Minor fixes

- docs/releases/upgrading/upgrade-v6.0.md
- requires https://github.com/inveniosoftware/invenio-app-rdm/pull/1015
- closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/202
> upgrade: v4 to v6 steps

- docs/reference/metadata.md
There is a lot of changes so here is a summary:
- reviewed and updated all the fields
- placed Parent and Access at the top: all related to pid/ids/each other + lighter definitions before the Metadata fields
- ordered the Metadata fields in the order of their appearance on the deposit page with the caveat that required fields are listed first
- removed the example full record (was out of date and no time to generate a full correct other one)
- removed files order and files meta sections. Both are not supported via the deposit page and not much tested recently.
- marked fields that are not on the deposit page as such (with the caveat that they might change)
- didn't document `props` of licenses (we don't want to expose it too much)
- removed vocabulary extension (we don't support it …
> reference: update for LTS

- docs/customize/search.md
- docs/install/run.md
- fix docs on faceting
- make need for authentication more explicit by adding curl header
will be merging this now
> global: improve customize/search + install/run docs

- docs/customize/authentication.md
Small updates based on experience at NU of setting up OIDC + wording fixes.
> authentication: update docs

- docs/reference/metadata.md
> metadata: fix additional lang and alt ids

- docs/customize/styling-templates.md
Fixes issues some people have been facing following the docs and trying to customize pages.
> customize-templates: fix instructions

- docs/customize/styling-theme.md
- docs/reference/metadata.md
Reverts inveniosoftware/docs-invenio-rdm#247
> Revert "Adds links to ID providers in reference/metadata"

- docs/reference/rest_api_requests.md
- REST: document requests API
- closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/263
> 263 requests api documentation

- docs/releases/upgrading/upgrade-v7.0.md
we found some differences in the ES mappings, so the ES indices need to be rebuilt
> upgrade: update the v6 to v7 migration

- docs/reference/index.md
- docs/reference/oai_pmh.md
- mkdocs.yml
> docs: add OAI-PMH reference guide

- docs/develop/topics/service.md
- update documentation to work with refactored configuration
* skipping involved details until the refactoring is more prevalent
- typos/wording pass
> develop: update service documentation for refactored config [+]

- docs/develop/getting-started/source-code.md
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/302
> Source code: update details

- docs/customize/index.md
- docs/customize/vocabularies/names.md
- mkdocs.yml
> customize: add names vocabulary docs

- docs/develop/getting-started/help.md
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
1. …
> Fixes wording?

- docs/customize/vocabularies/names.md
Although I'm not sure whether this link is the 'wanted' one.
> Removing 'TODO' to have a proper link.

- docs/develop/best-practices/accessibility.md
Updated aria-attributes example as it was not correct
> a11y: update aria-attr section

- docs/reference/rest_api_oaipmh_sets.md
- mkdocs.yml
Adds documentation for the OAI-PMH Sets REST API.
Including a warning that it is only available from version 9 onwards and the need for the `admin` role.
closes #317
**Reminder**
1. You license …
> docs: add oai-pmh rest api documentation

- docs/customize/index.md
- docs/customize/upload_limits.md
- mkdocs.yml
> Add documentation for setting file upload limits

- docs/reference/rest_api_members.md
- docs/reference/rest_api_reviews.md
- docs/releases/versions/version-v9.0.0.md
- mkdocs.yml
- references: reviews REST API
- references: typo fix in members
> Reviews REST API

- docs/develop/best-practices/i18n.md
Add warning for usage of f-string for i18n.
**Reminder** …
> i18n: add warning for f-strings

- docs/install/index.md
- docs/install/requirements.md
This PR adds some information on the requirements for an installation of InvenioRDM and a little bit of troubleshooting info.
> Installation Updates

- docs/customize/vocabularies/index.md
- docs/customize/vocabularies/resource_types.md
- mkdocs.yml
- General + resource type vocabulary customization updates
- Split the resource type content in its own file
> customize: update resource types docs

- docs/reference/rest_api_communities.md
closes #360
Section on featured communities API.
**Reminder**
2. You agree that you have the right to …
> docs: add section on featured communities API

- docs/reference/rest_api_communities.md
updated the api reference according to the current schema
closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/362
> community api reference: update schema

- docs/maintenance/demosite.md
Updated documentation url for open shift.
> maintenance: updated open shift urls

- docs/customize/record_landing_page.md
The variable for the default citation style has changed: https://github.com/inveniosoftware/invenio-app-rdm/blob/f76d1a2e679ddd61ca3991ab0e7938035f590758/invenio_app_rdm/records_ui/templates/semantic-ui/invenio_app_rdm/records/details/citation.html
> Update citation style variable

- docs/releases/upgrading/upgrade-v9.0.md
Given that https://github.com/inveniosoftware/invenio-userprofiles/pull/142 got merged, updating the specific branch is not needed anymore.
> release: update v9 upgrade docs

- docs/install/index.md
This is the result of feedback from the Open Repositories 2022
workshop.
> quickstart: quickstop

- docs/releases/upgrading/upgrade-v9.0.md
Add documentation for migration of older parent records.
related to: https://github.com/inveniosoftware/invenio-app-rdm/pull/1834
> add migration step for parent communities

- docs/customize/vocabularies/funding.md
This PR is updating the schema for funders, awards please check the [discord conversation](https://discord.com/channels/692989811736182844/704625518552547329/1014809781078347797)
**Reminder**
1. …
> funding: update awards and funders schema

- docs/customize/authentication.md
closes #400 
Add documentation for SAML `auto_confirm` variable.
Add to example config.
**Reminder**
2. …
> add documentation for SAML auto_confirm variable

- docs/reference/metadata.md
Change the PID example to match current InvenioRDM configuration and add additional configuration option details.
**Reminder**
1. You license your contribution under the same terms as the current …
> metadata: external DOI details

- docs/releases/upgrading/upgrade-v10.0.md
- mkdocs.yml
TODO: missing OpenSearch instructions.
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/1876
> upgrade: add upgrade guide v9 -> v10

- docs/customize/custom_fields/records.md
> Custom Fields: typo in example

- docs/customize/static_pages.md
- mkdocs.yml
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1934
> customize: add static pages docs

- docs/develop/best-practices/i18n.md
- docs/reference/cli.md
- closes https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/241
> best practices: add translations command to i18n section

- docs/develop/howtos/dev_email.md
- mkdocs.yml
> docs: added e-mail instructions for development.

- docs/develop/howtos/alembic.md
* closes https://github.com/inveniosoftware/invenio-pages/issues/54
> alembic: add how to create a branch

- docs/customize/custom_fields/records.md
Fix typo.
BTW the link in the "About" section of this repo points to the old RTD.
**Reminder**
> Fix small typo

- docs/customize/static_pages.md
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1989
> static-pages: update command

- docs/reference/metadata.md
The related identifiers schemes are out of date. This PR re-uses the alternative identifier list, which is in the correct order and has a helpful link.
**Reminder**
1. You license your …
> Update related identifier schemes

- docs/customize/static_pages.md
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1989
> Revert "static-pages: update command"

- docs/develop/howtos/route_migration.md
- mkdocs.yml
Added HOWTO documentations for url redirections (https://github.com/zenodo/zenodo-rdm/issues/104)
> url redirections: added howto docs.

- docs/develop/howtos/search_terms_migration.md
- mkdocs.yml
Added Howto documentation on search query parser https://github.com/zenodo/zenodo-rdm/issues/102
> seach: added query parser howto docs

- docs/install/index.md
- docs/install/requirements.md
Updated docs for issues regarding docker on linux.
> add: Documentation for setting-up docker on linux

- docs/releases/upgrading/upgrade-v11.0.md
- docs/releases/versions/version-v11.0.0.md
- closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/447
- closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/473
Requires:
- https://github.com/inveniosoftware/invenio-app-rdm/pull/2009
- #450 
- #462 
- https://github.com/inveniosoftware/docs-invenio-rdm/pull/465
> v11: added upgrade and release notes.

- docs/customize/authentication.md
It will fix the checkbox label from this:
to this:
**Reminder**
2. You agree that you have the right to …
> customize: fix auth custom reg form code

- docs/releases/versions/version-v11.0.0.md
Thank you for recognizing our contribution, I Change credit from Other to KTH Royal Institute of Technology
**Reminder**
1. You license your contribution under the same terms as the current …
> v11: fix KTH credit

- docs/customize/vocabularies/resource_types.md
Fixing my typo and rewording the group / independent section again :sweat_smile: .
Addresses https://discord.com/channels/692989811736182844/724974365451747329/1070040726680915998
> fix resource type typo

- docs/develop/howtos/override_components.md
Adhering to the outdated document directory structure will result in a failure during the webpack build process. To correct the mapping for the overridable Registry, it should be located within the assets instance directory.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions- …
> overrides: fix mapping for overridable Registry

- docs/reference/file_storage.md
- mkdocs.yml
- closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/483
> reference: file storage and storage class types

- docs/develop/architecture/event_handling.md
- mkdocs.yml
> architecture: add event handling

- docs/install/index.md
> Bump STS version to 11

- docs/customize/other-pids/urns.md
add thesis_types.yaml
fix link to custom_fields.md
**Reminder**
2. You agree that you have the right to …
> fix urn doc

- docs/develop/getting-started/package-development.md
- docs/develop/getting-started/source-code.md
Update outdated commands.
**Reminder**
2. You agree that you have the right to license your contribution …
> develop: update outdated commands

- docs/reference/metadata.md
Fix the structure of the contributor role to match the implementation https://github.com/inveniosoftware/invenio-rdm-records/blob/ab125a0ce966a1ba82f7f0e5457116f0f4922d88/tests/conftest.py#L417
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
> schema: fix structure of contributor role

- docs/customize/vocabularies/users.md
> users: add basic user management

- docs/customize/metadata_only.md
- mkdocs.yml
- Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2021.
**Reminder**
1. You license your contribution under the same terms as the …
> customize: metadata-only records flag

- docs/customize/vocabularies/resource_types.md
Add link to default resource type file
**Reminder**
2. You agree that you have the right to license your …
> resource_types: Add link to file

- docs/customize/vocabularies/resource_types.md
The current wording is unclear. If you pass `tags` with no values, the search will break. The expected behavior is to not pass `tags` at all.
**Reminder**
1. You license your contribution under …
> resource_types: Reword behavior without tags

- docs/customize/vocabularies/users.md
Add confirmed option, as demoed https://github.com/inveniosoftware/invenio-rdm-records/blob/master/tests/fixtures/app_data/users.yaml
**Reminder**
1. You license your contribution under the same …
> users: add confirmed option

- docs/develop/howtos/backup_search_indices.md
- docs/develop/howtos/i18n.md
- docs/reference/index.md
- docs/reference/rest_api_statistics.md
- docs/reference/statistics.md
- mkdocs.yml
This PR adds documentation for the usage statistics feature that's new in InvenioRDM v12.
> Statistics documentation

- docs/reference/rest_api_drafts_records.md
Update rest_api_drafts_records.md to include details of actions/files-import endpoint
**Reminder**
2. …
> drafts: document `actions/files-import` endpoint

- docs/customize/authentication.md
Adds some additional details about configuring SAML/Shibboleth
**Reminder**
> Add in additional details about configuring Shibboleth

- docs/install/run.md
Describe in the tutorial how to get a token, since it is needed by the next steps of the tutorial.
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
> Explain how to create a token

- docs/install/troubleshoot.md
While installing on a M1 machine, I stumbled upon this error:
```
pkg_resources.DistributionNotFound: The 'greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32"))))))' distribution was not found and is required by SQLAlchemy
```
As such, this PR suggests a possible workaround.
@ntarocco please let me know if this is the right place where to insert this info and if I need to specify a `sqlalchemy` version. 
Thanks!
If you've added [third-party code (copy/pasted or new …
> Add troubleshooting info for M1 install

- docs/customize/metadata/custom_fields/records.md
addresses https://github.com/zenodo/zenodo-rdm/issues/264
> custom-fields: add config for hiding fields in upload/landing page

- docs/install/scaffold.md
Document use_reduced_vocab option introduced in inveniosoftware/cookiecutter-invenio-rdm#266
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
> install: document use_reduced_vocabs options

- docs/reference/rest_api_communities.md
- docs/reference/rest_api_members.md
* resolves https://github.com/inveniosoftware/invenio-communities/issues/935
Adds docs for communities records and members endpoints
No.
> communities: add /records and /members docs

- docs/customize/authentication.md
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2186
> authentication: document that info has to return external id

- docs/install/requirements.md
This closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/432
It renames Elasticsearch to OpenSearch and changes the link to the documentation.
**Reminder**
1. You license your …
> Moving from Elasticsearch to OpenSearch

- docs/install/index.md
Closes https://github.com/inveniosoftware/docs-invenio-rdm/issues/565 
(and makes https://github.com/inveniosoftware/docs-invenio-rdm/pull/566 obsolete)
It suggestst to do the check-requirements --development after the scaffolding
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contribu …
> Splitting check-requirements and check-requirements --development

- docs/customize/vocabularies/users.md
* closes https://github.com/inveniosoftware/invenio-users-resources/issues/76
> updated: changed function param in accordance with this PR

- docs/customize/search.md
Add current supported search facets and sort options from https://github.com/inveniosoftware/invenio-rdm-records/blob/d1f55f95bde32963357eba8127acd06b82ea7be9/invenio_rdm_records/config.py#L232
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
> search: update facets and sort

- docs/install/scaffold.md
Add a bit more explanation based on https://github.com/inveniosoftware/invenio-app-rdm/issues/2377
**Reminder**
1. You license your contribution under the same terms as the current repository’s …
> scaffold: add more explanation

- docs/install/index.md
> index: document how to add first user in containerized application

- docs/maintenance/docker-images.md
Should be self explanatory: Fixed Typo in Markdown Link
**Reminder**
2. You agree that you have the …
> Typo in MD Link in docker-images.md

- docs/customize/vocabularies/users.md
- docs/install/index.md
This documents a simpler way for users following the installation instructions to create activated & confirmed users.
**Reminder**
2. You agree …
> install/users: document cli --confirm parameter for user creation

- docs/customize/vocabularies/users.md
We had some repetition between confirming and creating users. I've reorganized these sections so they flow better.
**Reminder**
1. You license your contribution under the same terms as the …
> users: reorganize account addition and confirmation

- docs/develop/architecture/communities.md
- docs/develop/architecture/event_handling.md
- docs/develop/architecture/index.md
- docs/develop/architecture/infrastructure.md
- docs/develop/architecture/reading.md
- docs/develop/architecture/records.md
- docs/develop/architecture/requests.md
- docs/develop/architecture/runtime.md
- docs/develop/architecture/software.md
Read through and improved the English in the Architecture section. I don't believe it needs much reviewing as it's all minor changes.
**Reminder**
1. …
> docs: Spelling and grammar in Architecture section

- docs/reference/rest_api_drafts_records.md
Add default search version behavior
**Reminder**
2. You agree that you have the right to license your …
> rest: add search default

- docs/customize/vocabularies/names.md
Closes [2545 ](https://github.com/inveniosoftware/invenio-app-rdm/issues/2545)
**Reminder**
2. You agree …
> Add missing id attribute to names vocabulary example

- docs/maintenance/release-management.md
> docs: improve release process

- docs/develop/howtos/override_components.md
I fixed the ID of the `metadataOnlyToggle` React component.
> fix wrong ID of overridable React component

- docs/reference/cli.md
Adds the Invenio RDM commands to the CLI reference. It includes commands for managing: 
- static pages
- creating fixtures
- rebuilding all indices
**Reminder**
1. You license your contribution …
> Add Invenio RDM commands to CLI reference

- docs/customize/vocabularies/index.md
Docs for [1303](https://github.com/inveniosoftware/invenio-rdm-records/pull/1303)
**Reminder**
2. You …
> fixtures: Implement add-to-fixture command

- docs/customize/vocabularies/funding.md
- docs/customize/vocabularies/names.md
- docs/reference/cli.md
- theme/frontpage_base.html
Closes [292](https://github.com/inveniosoftware/invenio-vocabularies/issues/292)
Closes [297](https://github.com/inveniosoftware/invenio-vocabularies/pull/297)
**Reminder**
1. You license your …
> vocabularies: add update flag to writers in YAML files

- .github/workflows/tests.yml
- docs/contribute/index.md
- docs/contribute/onboarding.md
- mkdocs.yml
- theme/frontpage_base.html
> onboarding: new section

- docs/customize/static_pages.md
* Update the documentation to incorporate the changes introduced in [2651](https://github.com/inveniosoftware/invenio-app-rdm/pull/2651)
* Added missing syntax highlighting to Markdown code blocks in static_pages page.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repo …
> Customize: Add Dynamic Registration Of Static Pages Through Config

- docs/maintenance/release-management.md
`invenio-users-resources` was not mentioned by the docs
> releases: add users resources

- docs/customize/vocabularies/affiliations.md
- docs/customize/vocabularies/funding.md
This is a start of the documentation for the new datastreams. If the http reader is merged, that should be used instead of having folks manually download the ROR data. Shouldn't be merged until https://github.com/inveniosoftware/invenio-vocabularies/pull/327
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> vocabularies: add datastreams info

- docs/develop/howtos/custom_code.md
https://github.com/pypa/pipenv/issues/6173
**Frontend**
**Reminder**
2. You agree that you have the right to license your …
> Fix: DataValidationError of pipenv

- docs/customize/dois.md
Add basic parent DOI explanation and update for v12.
**Frontend**
**Reminder**
2. You agree that you have the right to …
> Add parent doi explanation

- docs/reference/rest_api_communities.md
- docs/reference/rest_api_drafts_records.md
- docs/reference/rest_api_requests.md
- Changed expires_at from ISO 8601 DateTime to Date format to fix validation error.
- Removed `created_by.user`, `receiver.community`, and `topic.record` due to Unknown field validation errors.
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
> Update access link and requests examples

- docs/maintenance/release-management.md
This pull request adds documentation for the "Trunk based Development" as discussed by the community on [Discord](https://discord.com/channels/692989811736182844/704625518552547329/1247851765500612618). 
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
> Release: Add Trunk based Development Workflow

- docs/develop/getting-started/instance-development.md
* Development: Update Assets Watch Instructions
**Frontend**
**Reminder** …
> Development: Update Assets Watch Instructions

- docs/install/requirements.md
> backport: 25ef04b 582e994 f02d8a9

- docs/develop/howtos/dev_email.md
> email: add link

- docs/maintenance/modules.md
> docs: update GitHub link for flask-kvsession-invenio module

- docs/reference/oai_pmh.md
OAI-PMH: add XSL stylesheet instructions
example: https://zenodo.org/oai2d
**Reminder**
> OAI-PMH: add XSL stylesheet instructions

- docs/contribute/translators-guide.md
> docs: instruction on submitting translations for pages outside Transifex

- .github/dependabot.yml
- .github/workflows/tests.yml
Just an updated version of https://github.com/inveniosoftware/docs-invenio-rdm/pull/745
- rebased
- ubuntu-latest
- dependabot
Didn't want to force-push to your branch @tmorrell (maybe permissions would have prevented me, but it's nicer to not even try to force push onto other's branches), so I made a separate one.
**Reminder**
2. You agree that you have the right to license your …
> Updated "tests: update ubuntu version "

- docs/releases/v13/version-v13.0.0.md
* Fixes inveniosoftware/invenio-app-rdm#2937
**Reminder**
> v13: FAIR signposting level 1 (config flag & nginx config)

- docs/community/translations/translators-guide.md
* as we discuss in the Telecon call, translation requests should come via the translation Discord channel; at least one known contributor must vouch for the new person before Transifex access is granted (“trust-chain” model).
**Reminder**
> i18n: add chain of trust step

- docs/reference/rest_api_drafts_records.md
> API: add persistent identifiers and DOI management in draft records

- docs/develop/howtos/search_templates.md
- mkdocs.yml
> Mesh research/master

- docs/customize/authentication.md
Broken link on the authentication page after version links changed.
**Reminder**
> fix: v9 link on authentication page

- docs/install/build-setup-run.md
- docs/install/index.md
- Small typing change for build options. 
- Added instruction to `navigate into your new instance` after initialization.
- Moved `invenio-cli check-requirements --development` to after project initialization, it requires the created project.
**Reminder**
> install: improve instructions

- docs/releases/v13/version-v13.0.0.md
> v13: add logging improvement to release notes

- docs/operate/customize/vocabularies/affiliations.md
- docs/operate/customize/vocabularies/funding.md
- docs/releases/v13/upgrade-v13.0.md
- docs/releases/v13/version-v13.0.0.md
Suggests using invenio-jobs for affiliations and funders vocabularies.
**Reminder**
> vocabularies: add invenio-jobs for affilliations and funders

- docs/community/documentation.md
> documentation: list places to update when doc links change

- docs/operate/customize/dois.md
This integrates the new optional DOI section into the rest of the DOI documentation. Having the full variables is needed to have the configuration work correctly.
**Reminder**
> dois: update to have a fully working optional parent doi workflow

- docs/operate/customize/file-uploads/s3.md
Update some wording in the text about S3, and provide a URL for the AGPLv3 license.
> S3: Update some wording

- docs/releases/v13/upgrade-v13.0.md
v13 will need invenio-cli 1.8+
**Reminder**
> upgrade: bump invenio-cli version for v13
